travis:
  secure:
    BINSTAR_TOKEN: tOpwadfM7DdDSg/RChdnQZz2U/LkyeILehdfC9Gof1r46KdlLFSO5LcDrReGC2vG3pl2xRWTDKDS//qo6bKp5J4qpLQdcRLMCBpmUomiltEKaua/+NK94G0CMNcJviaLWBleWuBeb2IrR0LC2YnO7PMkrEaiVDE3tj5trt+ZbbT40pXT/4NKET8dSQVLKp3WRmOs/R0EyMpnyNF8rxJSFqaxIBjia6EpkJpc21ZY5ZM560Mvm4bEO58kj9L1EmaYQzGsyIIkPSjoRQW8VYbHyWu6MK7nSnR+8T3Nlo+3OvZb4arNAOMkpUWXMz5Q1KAZKu7nYOJRUh5u+Mk/eDsejnebxfd3RGvJSef0wIisMTKFybFVGWdBa5MRK4k1lWoECeBdjjV6db7XFw58DmflyoBz/VwsYC08KJhuVFXT4giPRVRvcuNP0fhEFVC0oS5H6o4CmaFMn0gfYeQgrA8vFBFtsmt9xFI81pTEwB+FaSsSgjldhQevYbULV+oW9RBlygm73rPGfbwzT0HrNI3KW5+uu1SfBJLjRYEpi4xIvio/lZ3OSCgKxgho80GyeZKxk8FKKe1qc6qdPM+f2f7UpNoXx4T7ABWx5gJaFXNkMewFDrSf/rab9h+jb3WgcRahDZAk+xDGF19gEca+XRpkIZDQ+IlslH5t7pmT1uFVd1Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
